### ISSUE TITLE
安裝之後 雖然有框框但無須輸入仍可登入註冊

### ISSUE THREAD

**Issue by chickentw** [popcorner/discuz_recaptcha#2]
一直被各種廣告困擾，發現這個插件之後就安裝試試了，但還是一樣

後來發現，不需要通過驗證就可以登入了。

演示影片（需翻牆）：
https://drive.google.com/open?id=1ScTyhI-52iu9Vto3_r9JNCUqh_yZDxgh

嘗試過github版本和dismall上的版本，都有一樣的問題

**Comment by popcorner** [comment]
翻不动╮(╯▽╰)╭
正常情况下是不应该出现这种事情的，方便给个网站地址看下么？这个插件有很多人装过，但并没有出现类似的问题

**Comment by chickentw** [comment]
好的 網址：https://www.doratown.net/bbs/

recaptcha後台也顯示出這個問題
<img width="1057" alt="截圖 2019-12-31 上午3 12 26" src="https://user-images.githubusercontent.com/1430471/71596736-65604080-2b7b-11ea-9736-028bc61fb6fa.png">

**Comment by popcorner** [comment]
看到了，这个问题确实存在。你这个运行时候的表现，就跟其他装了这个插件的站完全不一样。你试试运行一下后台的更新缓存再试试看？这个不像是我这个插件的bug，更像是环境问题

**Comment by chickentw** [comment]
試過更新緩存

好吧，我從環境的部分排除看看，感謝那麼晚了還回覆那麼快
