### ISSUE TITLE
1.13版本 discuz X3.4无法使用

### ISSUE THREAD

**Issue by ghost** [popcorner/discuz_recaptcha#3]
如题，刷新不出验证码，看控制台recaptcha.js有一个报错，由于我不会PHP，没办法了解更多。
希望作者能修复，感谢。

**Comment by popcorner** [comment]
至少把现象描述的具体一点才好回答呀，比方说报错到底是什么样子的。这样的话我也没办法了解更多……
插件本身有问题的可能性不是很大，因为很多人都在用这个插件，都能正常使用。
首先确定不是以下问题：低版本php（这个插件在上古版本的php里运行可能会有问题），域名问题（后台可以切换域名，试试其他的域名是否可以），浏览器问题（换别的浏览器试试是否正常）

**Comment by ghost** [comment]
PHP 7.0
Discuz X3.4 20191201 新安装
现象：刷不出验证码，控制台报错
> SyntaxError: unexpected token: identifier

定位一下，发现问题发生在

> <img src="template/mystyle/image$(showid).innerHTML = string;setTimeout(

这里

**Comment by ghost** [comment]
你可以访问：bbs.cubeworld.cc
我已经把它装在上面了，现在可以复现

**Comment by popcorner** [comment]
你的imgdir设置是啥？
另外可以尝试随便改动一点插件的设置，然后保存一下，再试试看

**Comment by ghost** [comment]
imgdir设置的是
> template/cwstyle/image/

插件的配置，我已经关闭了“加载图标”和“帮助图标”两项，但依然有这个问题。

**Comment by popcorner** [comment]
那这就是问题了。imgdir设置的时候，最后是不应该有斜杠的。你去掉试试看。

**Comment by ghost** [comment]
还真是......
学到了，非常感谢！
