### ISSUE TITLE
Discuz X3.4点击验证成功登录时候又提示验证码错误

### ISSUE THREAD

**Issue by jianshan123** [popcorner/discuz_recaptcha#4]
我的discuz X3.4新版本，安装这个插件启用后
点击登录或发表信息验证成功了，但点击下一步就会又提示错误，这样反复，没法进行下一步操作怎么办？

**Comment by popcorner** [comment]
是Discuz X3.4 20191201么？验证成功但提示错误可能是服务器和google之间的通信问题，也可能是别的问题，如php版本太低等。插件本身可以在这个版本的Discuz上正常工作的。

**Comment by jianshan123** [comment]
> 是Discuz X3.4 20191201么？验证成功但提示错误可能是服务器和google之间的通信问题，也可能是别的问题，如php版本太低等。插件本身可以在这个版本的Discuz上正常工作的。

我把php5升级到了php7也还不行，该怎么办？

**Comment by popcorner** [comment]
> 我把php5升级到了php7也还不行，该怎么办？

那可以尝试排查一下问题的来源。至少按照你所提供的信息进行安装使用的话，是无法复现出这种问题的。

**Comment by laozhoubuluo** [comment]
> 
> 
> > 是Discuz X3.4 20191201么？验证成功但提示错误可能是服务器和google之间的通信问题，也可能是别的问题，如php版本太低等。插件本身可以在这个版本的Discuz上正常工作的。
> 
> 我把php5升级到了php7也还不行，该怎么办？

试试升级到Discuz! X3.4 20191201，并关闭其他验证码后能否解决。
(其实这条我5月18日就回复邮件了，不知道为啥GitHub没给我生成回复......
