### ISSUE TITLE
有的模版装不了 

### ISSUE THREAD

**Issue by cgfor** [popcorner/discuz_recaptcha#5]
这个插件太好用了 但是有的模版 好像装不了啊 。。不清楚缺少了哪个部分 。能付费求助吗

**Comment by cgfor** [comment]
手机模版 也没有报错 在后台可以正常显示  在前端就显示 【一个输入框 右边的图片挂掉】 什么错误也没看到。。。。

一个电脑模版可用
  （另一个站电脑模版 提示js错误 Uncaught SyntaxError: Unexpected identifier 
var r9=$('seccodeverify_'+idhash).form;if(r9&&!r9.hasAttribu）

**Comment by popcorner** [comment]
我这个是走的是discuz的标准接口，正常来说大部分模板都应该直接兼容的。
如果第三方模板乱搞导致无法兼容的话那我也没办法呀。
