### ISSUE TITLE
正常设置后无法使用 Google reCAPTCHA

### ISSUE THREAD

**Issue by yiqiehuanying** [popcorner/discuz_recaptcha#6]
按照要求设置 Google reCAPTCHA 插件后提示错误从而无法使用插件。
公钥、密钥均已按要求规范设置。

**Comment by yiqiehuanying** [comment]
为什么我一发issues就可以用了***
抱歉打扰了

**Comment by popcorner** [comment]
大概率不是插件的问题。刚看了一下，今天谷歌验证码的国内cdn在部分运营商那里出现了解析异常的情况（主要是电信和部分省的移动），导致验证码无法加载。此问题与插件无关，你可以尝试使用119.29.29.29等较为可靠的公共dns再试试看。

**Comment by popcorner** [comment]
更新：上述问题应该已经没有了

**Comment by yiqiehuanying** [comment]
> 更新：上述问题应该已经没有了

感谢 马上就把issues关了  :+1: 
给大佬加披萨UwU :pizza: :pizza: :pizza:
