### ISSUE TITLE
手机无法验证

### ISSUE THREAD

**Issue by yiqiehuanying** [popcorner/discuz_recaptcha#7]
如题，手机无法正常进行验证

![forum heterocraft com_member php_mod=logging action=login mobile=yes](https://user-images.githubusercontent.com/60646086/115947154-516ee980-a4f8-11eb-91e9-49548b529fca.png)

**Comment by popcorner** [comment]
首先确认插件后台已开启手机版开关，就可以验证了。
注意：如果用的是v3版本，目前不支持手机。
如果使用了第三方手机模板或手机相关插件，有可能存在导致冲突的可能性，此时需要自行排查解决，与本插件无关。

**Comment by yiqiehuanying** [comment]
已解决 抱歉qwq
