### ISSUE TITLE
如何修改url

### ISSUE THREAD

**Issue by LiuNianJiang** [popcorner/discuz_recaptcha#8]
作者你好，我将staticurl修改成静态资源托管地址后，发现插件无法正常工作，请问如何才能够修改url变成我原先的地址

**Comment by popcorner** [comment]
使用自建CDN来托管站内静态资源的时候，应该将js目录指向data/cache而非static/js。

**Comment by LiuNianJiang** [comment]
> 使用自建CDN来托管站内静态资源的时候，应该将js目录指向data/cache而非static/js。

我是把js资源直接放在了GitHub上面并且使用公共库进行加速，这样子好像必须要static/js，请问配置内可以修改么？

**Comment by popcorner** [comment]
> > 使用自建CDN来托管站内静态资源的时候，应该将js目录指向data/cache而非static/js。
> 
> 我是把js资源直接放在了GitHub上面并且使用公共库进行加速，这样子好像必须要static/js，请问配置内可以修改么？

目前没有这种功能，如果使用静态CDN的话可以尝试去data/cache里查找对应的js（可以在浏览器控制台查看到具体缺少的js）然后复制进去。
插件的设置会直接写进js并缓存，因此每次修改设置后需要重新替换一次js。

此外如果你使用的是我这边出的公共版的CDN的话（ https://www.dismall.com/thread-9034-1-1.html ），目前暂时没有办法支持。
我这边后续会出一个自定义的功能。

**Comment by LiuNianJiang** [comment]
> > > 使用自建CDN来托管站内静态资源的时候，应该将js目录指向data/cache而非static/js。
> > 
> > 
> > 我是把js资源直接放在了GitHub上面并且使用公共库进行加速，这样子好像必须要static/js，请问配置内可以修改么？
> 
> 目前没有这种功能，如果使用静态CDN的话可以尝试去data/cache里查找对应的js（可以在浏览器控制台查看到具体缺少的js）然后复制进去。
> 插件的设置会直接写进js并缓存，因此每次修改设置后需要重新替换一次js。
> 
> 此外如果你使用的是我这边出的公共版的CDN的话（ https://www.dismall.com/thread-9034-1-1.html ），目前暂时没有办法支持。
> 我这边后续会出一个自定义的功能。

已经上传了，文件加载也是成功的，但是还是验证失败
控制台报错：Uncaught SyntaxError: Unexpected identifier

**Comment by popcorner** [comment]
> 已经上传了，文件加载也是成功的，但是还是验证失败
> 控制台报错：Uncaught SyntaxError: Unexpected identifier

那你可能需要重新填写一次设置并保存，然后再去试试新生成的js。

**Comment by LiuNianJiang** [comment]
> 那你可能需要重新填写一次设置并保存，然后再去试试新生成的js。

尝试了一下，还是不行

**Comment by popcorner** [comment]
> 尝试了一下，还是不行

那建议尝试一下清理缓存，确认一下使用的插件文件是否有异常，如果还是不行的话可以考虑将网站发出来。
插件应该是都能正常工作的，这个插件发布很长时间了也很多人在用，本身估计是没有问题。

**Comment by LiuNianJiang** [comment]
> 那建议尝试一下清理缓存，确认一下使用的插件文件是否有异常，如果还是不行的话可以考虑将网站发出来。
> 插件应该是都能正常工作的，这个插件发布很长时间了也很多人在用，本身估计是没有问题。

bbs.x64.site

**Comment by LiuNianJiang** [comment]
> > 尝试了一下，还是不行
> 
> 那建议尝试一下清理缓存，确认一下使用的插件文件是否有异常，如果还是不行的话可以考虑将网站发出来。
> 插件应该是都能正常工作的，这个插件发布很长时间了也很多人在用，本身估计是没有问题。

你好，加一下联系方式可以嘛，因为不能一直开着没法用的recaptcha
我把recaptcha托管到GitHub并且使用jsdelivr加速，但是一直显示错误

**Comment by popcorner** [comment]
> 你好，加一下联系方式可以嘛，因为不能一直开着没法用的recaptcha
> 我把recaptcha托管到GitHub并且使用jsdelivr加速，但是一直显示错误

检查一下你的IMGDIR配置，大概率是你写错了。
如我上面提到的 https://www.dismall.com/thread-9034-1-1.html 所示，IMGDIR和另外2项静态资源不同，最后**一定不能加**斜杠。

参考： #3

**Comment by LiuNianJiang** [comment]
> > 你好，加一下联系方式可以嘛，因为不能一直开着没法用的recaptcha
> > 我把recaptcha托管到GitHub并且使用jsdelivr加速，但是一直显示错误
> 
> 检查一下你的IMGDIR配置，大概率是你写错了。
> 如我上面提到的 https://www.dismall.com/thread-9034-1-1.html 所示，IMGDIR和另外2项静态资源不同，最后**一定不能加**斜杠。
> 
> 参考： #3

确实此处我加了斜杠
我删掉斜杠并更新缓存后，还是一样的报错
是不是目前根本不支持将recaptcha.js托管到GitHub这个方法？

**Comment by popcorner** [comment]
> 确实此处我加了斜杠
> 我删掉斜杠并更新缓存后，还是一样的报错
> 是不是目前根本不支持将recaptcha.js托管到GitHub这个方法？

你至少应该把文件给更新了再测试吧……
https://github.com/huang545/bbs/blob/main/static/js/recaptcha.js
你看这最后修改时间

**Comment by LiuNianJiang** [comment]
> > 确实此处我加了斜杠
> > 我删掉斜杠并更新缓存后，还是一样的报错
> > 是不是目前根本不支持将recaptcha.js托管到GitHub这个方法？
> 
> 你至少应该把文件给更新了再测试吧……
> https://github.com/huang545/bbs/blob/main/static/js/recaptcha.js
> 你看这最后修改时间

Uncaught SyntaxError:     recaptcha.js?F03:1
还是这个操作，我删除了文件，保存了设置，再从cache下面下载了js，随后上传GitHub，依然是这样子报错

**Comment by popcorner** [comment]
> Uncaught SyntaxError: recaptcha.js?F03:1
> 还是这个操作，我删除了文件，保存了设置，再从cache下面下载了js，随后上传GitHub，依然是这样子报错

https://cdn.jsdelivr.net/gh/huang545/bbs@main/static/js/recaptcha.js
你实际调用的是这个对吧，你对比一下看跟你上传的一样么……

**Comment by LiuNianJiang** [comment]
> > Uncaught SyntaxError: recaptcha.js?F03:1
> > 还是这个操作，我删除了文件，保存了设置，再从cache下面下载了js，随后上传GitHub，依然是这样子报错
> 
> https://cdn.jsdelivr.net/gh/huang545/bbs@main/static/js/recaptcha.js
> 你实际调用的是这个对吧，你对比一下看跟你上传的一样么……

不一样。。。。。。我只能等缓存失效之后再试试了

**Comment by LiuNianJiang** [comment]
问题已经解决
cdn缓存过期后已经可以正常使用，谢谢！
